### ISSUE TITLE
Make sharing picture via email nicer

### ISSUE THREAD

**Issue by lhirlimann** [mozilla/f1#25]
Right now sharing an image by email (at least from flickr) just sends a link, would be nice to embed the image.

**Comment by clarkbw** [comment]
initial commit of 4c36b34b5f37da4f72ea1dc3e612882f231116b7 adds support to the backend for sending images as inline attachments in HTML emails.  Further works is needed before this is ready.
- Only Photos and Videos / Site provided images are really useful.  The small screenshots of sites provide very little visual value.  I think we can try sending screenshots for a little while but ultimately it might be best to just not include them.
- James is working on the Image -> base64 converter using Canvas which will enable us to use the site provided images in emails.
- Andy probably wants to take a look at the html email file if there are any changes to the style that was originally done
- Yahoo email doesn't use the MIME system which is wonderful but at the same time difficult to understand how to go about making it work with their jsonrpc system.  Since I've already descended several rings into hell by using the MIME system I'd love to reuse that work if possible.

**Comment by clarkbw** [comment]
James added commit e711b09c7789fc260a8fd213bfa843fd057923aa which lands support for images provided by the site.

**Comment by clarkbw** [comment]
There is still an issue that Yahoo doesn't use the image provided but otherwise this is fixed.
